<a href="https://colab.research.google.com/github/monajalal/pytorch_playground/blob/master/Learn_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision

    100% |████████████████████████████████| 519.5MB 31kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5915c000 @  0x7f0abd7e02a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641
    100% |████████████████████████████████| 61kB 20.5MB/s 
    100% |████████████████████████████████| 2.0MB 4.3MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import torch
from IPython.core.debugger import set_trace

def f(x):
  res = x * x
  set_trace()
  return res
x = torch.rand(1, requires_grad=True)
y = f(x)

> <ipython-input-2-1a65bb5f8a53>(7)f()
      5   res = x * x
      6   set_trace()
----> 7   return res
      8 x = torch.rand(1, requires_grad=True)
      9 y = f(x)

ipdb> x
tensor([0.7549], requires_grad=True)
ipdb> y
*** NameError: name 'y' is not defined
ipdb> res
tensor([0.5699], grad_fn=<ThMulBackward>)
--KeyboardInterrupt--
--KeyboardInterrupt--
--KeyboardInterrupt--


In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [0]:
from collections import OrderedDict

layers = OrderedDict([
    ('conv1', nn.Conv2d(in_channels=1, out_channels=20, kernel_size=5)),
    ('relu1', nn.ReLU()),
    ('conv2', nn.Conv2d(20, 64, 5)),
    ('relu2', nn.ReLU())
])

model = nn.Sequential(layers)

In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5)
    self.pool = nn.MaxPool2d(2, 2)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)
    self.fc1 = nn.Linear(in_features=16*5*5, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=84)
    self.fc3 = nn.Linear(in_features=84, out_features=10)
  def forward(self, x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16*5*5)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
  
net = Net()

In [4]:
import torch
torch.__version__

'0.4.1'

In [5]:
import torchvision
torchvision.__version__

'0.2.1'

In [0]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
x = np.random.random([5, 3])
x

array([[0.94851125, 0.30929362, 0.80208999],
       [0.9448203 , 0.98330745, 0.5101267 ],
       [0.1958379 , 0.71690683, 0.4869872 ],
       [0.50045586, 0.40912449, 0.27877903],
       [0.04848507, 0.31421529, 0.41400702]])

In [14]:
y = torch.rand([5, 3])
y

tensor([[0.0669, 0.0637, 0.8578],
        [0.5033, 0.2574, 0.2040],
        [0.0980, 0.9306, 0.3151],
        [0.5579, 0.4278, 0.8343],
        [0.8245, 0.0167, 0.8839]])

In [15]:
print(x.shape)
print(y.shape)

(5, 3)
torch.Size([5, 3])


In [16]:
x.T @ x

array([[2.08351835, 1.58279834, 1.49772976],
       [1.58279834, 1.84262557, 1.34295981],
       [1.49772976, 1.34295981, 1.3898537 ]])

In [17]:
y.t() @ y

tensor([[1.2584, 0.4774, 1.3851],
        [0.4774, 1.1196, 0.7721],
        [1.3851, 0.7721, 2.3540]])

In [18]:
inv(x.T @ x)

array([[ 2.29463711, -0.57095557, -1.92104816],
       [-0.57095557,  1.9770045 , -1.29502871],
       [-1.92104816, -1.29502871,  4.04098828]])

In [19]:
torch.inverse(y.t() @ y)

tensor([[ 2.2589, -0.0603, -1.3094],
        [-0.0603,  1.1558, -0.3436],
        [-1.3094, -0.3436,  1.3080]])

In [20]:
from torch import autograd

w= torch.ones(1)
w.requires_grad

False

In [21]:
z = torch.ones(1)*2
z.requires_grad

False

In [22]:
total = w + z
total.requires_grad

False

In [23]:
total.backward()

RuntimeError: ignored

In [26]:
w= torch.ones(1, requires_grad=True)
z = torch.ones(1, requires_grad=True)*2
total = w + z
total.backward()
w.grad

tensor([1.])

In [27]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [28]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')